=== svrooij/sonos-api-docs/docs/schema/documentation.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://svrooij.io/sonos-api-docs/schema/documentation.json",
  "definitions": {
    "SonosServiceDocumentation": {
      "title": "Service name",
      "description": "The name of the service should match exactly to the name in the Service Discovery",
      "properties": {
        "actions": {
          "title": "Actions in this service",
          "additionalProperties": {
            "$ref": "#/definitions/SonosServiceDocumentationAction"
          },
          "type": "object"
        },
        "description": {
          "type": "string"
        },
        "errors": {
          "title": "Custom errors for this service",
          "type": "array",
          "items": {
            "$ref": "#/definitions/SonosCustomError"
          }
        }
      },
      "type": "object",
      "required": ["description"]
    },
    "SonosServiceDocumentationAction": {
      "title": "Action name",
      "description": "The name of the action should match exactly with the Service Discovery",
      "properties": {
        "description": {
          "title": "Short description of action",
          "type": "string"
        },
        "params": {
          "title": "Action parameters",
          "additionalProperties": {
            "title": "Parameter description",
            "description": "Describe a single input/output argument, by it name as key",
            "type": "string"
          },
          "type": "object"
        },
        "remarks": {
          "title": "Action remarks",
          "description": "Remarks about this action",
          "type": "string"
        }
      },
      "type": "object",
      "required": ["description"]
    },
    "SonosCustomError": {
      "title": "Custom error",
      "description": "Sonos defined custom errors per UPNP Service.",
      "properties": {
        "code": {
          "title": "Error code",
          "type": "number"
        },
        "description": {
          "title": "Error description",
          "type":"string"
        }
      },
      "type": "object",
      "required": ["code", "description"]
    }
  },
  "properties": {
    "license": {
      "title": "License of the current documentation, MIT is required to be included into the generator",
      "type": "string",
      "default": "MIT"
    },
    "language": {
      "type": "string",
      "title": "Language of the current documentation"
    },
    "services": {
      "title": "Each service is added with it's name as key",
      "additionalProperties": {
        "$ref": "#/definitions/SonosServiceDocumentation"
      },
      "type": "object"
    },
    "errors": {
      "title": "Default errors",
      "description": "These errors are used in all services.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/SonosCustomError"
      }
    }
  },
  "type": "object",
  "required": ["license", "services", "language"]
}

=== svrooij/sonos-api-docs/docs/documentation.json
{
  "$schema": "https://sonos.svrooij.io/schema/documentation.json",
  "language": "EN",
  "license": "MIT",
  "services": {
    "AlarmClockService": {
      "description": "Control the sonos alarms and times",
      "actions": {
        "CreateAlarm": {
          "description": "Create a single alarm, all properties are required",
          "params": {
            "StartLocalTime": "The start time as `hh:mm:ss`",
            "Duration": "The duration as `hh:mm:ss`",
            "Recurrence": "Repeat this alarm on",
            "Enabled": "Alarm enabled after creation",
            "RoomUUID": "The UUID of the speaker you want this alarm for",
            "ProgramURI": "The sound uri",
            "ProgramMetaData": "The sound metadata, can be empty string",
            "PlayMode": "Alarm play mode",
            "Volume": "Volume between 0 and 100",
            "IncludeLinkedZones": "Should grouped players also play the alarm?",
            "AssignedID": "The ID of the new alarm"
          },
          "sample": {
            "StartLocalTime": "07:00:00",
            "Duration": "00:30:00",
            "Recurrence": "DAILY",
            "Enabled": "1",
            "RoomUUID": "RINCON_000E58FE3AEA01400",
            "ProgramURI": "x-rincon-buzzer:0",
            "ProgramMetaData": "",
            "PlayMode": "NORMAL",
            "Volume": "20",
            "IncludeLinkedZones": "1",
            "AssignedID": "1"
          }
        },
        "DestroyAlarm": {
          "description": "Delete an alarm",
          "params": {
            "ID": "The Alarm ID from ListAlarms"
          }
        },
        "ListAlarms": {
          "description": "Get the AlarmList as XML",
          "params": {
            "CurrentAlarmList": "xml string, see remarks"
          },
          "remarks": "Some libraries also provide a ListAndParseAlarms where the alarm list xml is parsed"
        },
        "UpdateAlarm": {
          "description": "Update an alarm, all parameters are required.",
          "params": {
            "ID": "The ID of the alarm see ListAlarms",
            "StartLocalTime": "The start time as `hh:mm:ss`",
            "Duration": "The duration as `hh:mm:ss`",
            "Recurrence": "Repeat this alarm on",
            "Enabled": "Alarm enabled after creation",
            "RoomUUID": "The UUID of the speaker you want this alarm for",
            "ProgramURI": "The sound uri",
            "ProgramMetaData": "The sound metadata, can be empty string",
            "PlayMode": "Alarm play mode",
            "Volume": "Volume between 0 and 100",
            "IncludeLinkedZones": "Should grouped players also play the alarm?"
          },
          "remarks": "Some libraries support PatchAlarm where you can update a single parameter"
        }
      },
      "errors": [{ "code": 801, "description": "Duplicate alarm time" }]
    },
    "AudioInService": {
      "description": "Control line in"
    },
    "AVTransportService": {
      "description": "Service that controls stuff related to transport (play/pause/next/special URLs)",
      "actions": {
        "AddURIToQueue": {
          "description": "Adds songs to the SONOS queue",
          "remarks": "In NORMAL play mode the songs are added prior to the specified `DesiredFirstTrackNumberEnqueued`.",
          "params": {
            "DesiredFirstTrackNumberEnqueued": "use `0` to add at the end or `1` to insert at the beginning"
          }
        },
        "BecomeCoordinatorOfStandaloneGroup": {
          "description": "Leave the current group and revert to a single player."
        },
        "ConfigureSleepTimer": {
          "description": "Stop playing after set sleep timer or cancel",
          "remarks":"Send to non-coordinator returns error code 800",
          "params": {
            "NewSleepTimerDuration": "Time to stop after, as `hh:mm:ss` or empty string to cancel"
          }
        },
        "DelegateGroupCoordinationTo": {
          "description": "Delegates the coordinator role to another player in the same group",
          "remarks":"Send to non-coordinator has no results - should be avoided.",
          "params": {
            "NewCoordinator": "uuid of the new coordinator - must be in same group",
            "RejoinGroup": "Should former coordinator rejoin the group?"
          }
        },
        "GetCrossfadeMode": {
          "description": "Get crossfade mode",
          "remarks":"Send to non-coordinator may return wrong value as only the coordinator value in a group"
        },
        "GetCurrentTransportActions": {
          "description": "Get current transport actions such as Set, Stop, Pause, Play, X_DLNA_SeekTime, Next, X_DLNA_SeekTrackNr",
          "remarks":"Send to non-coordinator returns only `Start` and `Stop` since it cannot control the stream."
        },
        "GetMediaInfo": {
          "description": "Get information about the current playing media (queue)"
        },
        "GetPositionInfo": {
          "description": "Get information about current position (position in queue and time in current song)"
        },
        "GetRemainingSleepTimerDuration": {
          "description": "Get time left on sleeptimer.",
          "remarks":"Send to non-coordinator returns error code 800",
          "params": {
            "RemainingSleepTimerDuration": "Format hh:mm:ss or empty string if not set"
          }
        },
        "GetTransportInfo": {
          "description": "Get current transport status, speed and state such as PLAYING, STOPPED, PLAYING, PAUSED_PLAYBACK, TRANSITIONING, NO_MEDIA_PRESENT",
          "remarks":"Send to non-coordinator always returns PLAYING"
        },
        "GetTransportSettings": {
          "description": "Get transport settings",
          "remarks":"Send to non-coordinator returns the settings of it's queue"
        },
        "Next": {
          "description": "Go to next song",
          "remarks": "Possibly not supported at the moment see GetCurrentTransportActions"
        },
        "Pause": {
          "description": "Pause playback"
        },
        "Play": {
          "description": "Start playing the set TransportURI",
          "params": {
            "Speed": "Play speed usually 1, can be a fraction of 1"
          }
        },
        "Previous": {
          "description": "Go to previous song",
          "remarks": "Possibly not supported at the moment see GetCurrentTransportActions"
        },
        "RemoveAllTracksFromQueue": {
          "description": "Flushes the SONOS queue.",
          "remarks":"If queue is already empty it throw error 804. Send to non-coordinator returns error code 800."
        },
        "RemoveTrackRangeFromQueue": {
          "description": "Removes the specified range of songs from the SONOS queue.",
          "params": {
            "UpdateID": "Leave blank",
            "StartingIndex": "between 1 and queue-length"
          }
        },
        "SaveQueue": {
          "description": "Saves the current SONOS queue as a SONOS playlist and outputs objectID",
          "remarks":"Send to non-coordinator returns error code 800",
          "params": {
            "Title": "SONOS playlist title", 
            "ObjectID": "Leave blank"
          }
        },
        "Seek": {
          "description": "Seek track in queue, time delta or absolute time in song",
          "remarks":"Returns error code 701 in case that content does not support Seek or send to non-coordinator",
          "params": {
            "Unit": "What to seek",
            "Target": "Position of track in queue (start at 1) or `hh:mm:ss` for `REL_TIME` or `+/-hh:mm:ss` for `TIME_DELTA`"
          }
        },
        "SetAVTransportURI": {
          "description": "Set the transport URI to a song, a stream, the queue, another player-rincon and a lot more",
          "remarks":"If set to another player RINCON, the player is grouped with that one.",
          "params": {
            "CurrentURI": "The new TransportURI - its a special SONOS format",
            "CurrentURIMetaData": "Track Metadata, see MetadataHelper.GuessTrack to guess based on track uri"
          }
        },
        "SetCrossfadeMode": {
          "description": "Set crossfade mode",
          "remarks":"Send to non-coordinator returns error code 800. Same for content, which does not support crossfade mode."
        },
        "SetPlayMode": {
          "description": "Set the PlayMode",
          "remarks":"Send to non-coordinator returns error code 712. If SONOS queue is not activated returns error code 712.",
          "params": {
            "NewPlayMode": "New playmode"
          }
        },
        "SnoozeAlarm": {
          "description": "Snooze the current alarm for some time.",
          "params": {
            "Duration": "Snooze time as `hh:mm:ss`, 10 minutes = 00:10:00"
          }
        },
        "Stop": {
          "description": "Stop playback"
        }
      },
      "errors": [
        { "code": 701, "description": "Transition not available" },
        { "code": 702, "description": "No content" },
        { "code": 703, "description": "Read error" },
        { "code": 704, "description": "Format not supported for playback" },
        { "code": 705, "description": "Transport is locked" },
        { "code": 706, "description": "Write error" },
        { "code": 707, "description": "Media protected or not writeable" },
        { "code": 708, "description": "Format not supported for recording" },
        { "code": 709, "description": "Media is full" },
        { "code": 710, "description": "Seek mode not supported" },
        { "code": 711, "description": "Illegal seek target" },
        { "code": 712, "description": "Play mode not supported" },
        { "code": 713, "description": "Record quality not supported" },
        { "code": 714, "description": "Illegal MIME-Type" },
        { "code": 715, "description": "Content busy" },
