=== svrooij/sonos-api-docs/docs/schema/template.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://svrooij.io/sonos-api-docs/schema/template.json",
  "definitions": {
    "TemplateFile": {
      "properties": {
        "file": {
          "title": "Template filename",
          "type": "string"
        },
        "outputFile": {
          "title": "Output filename",
          "description": "How to output the file(s), '{service}' is replaced by the serviceName, '{snService}' is replaced by snakecase service name",
          "type": "string"
        },
        "usage": {
          "title": "Template use",
          "description": "Is this template used for all services combined of per service",
          "type": "string",
          "enum": [
            "index",
            "service"
          ]
        }
      },
      "required": [
        "file",
        "outputFile",
        "usage"
      ],
      "type": "object"
    }
  },
  "title": "Template configuration",
  "properties": {
    "author": {
      "$ref": "author.json"
    },
    "files": {
      "title": "Templates to process",
      "items": {
        "$ref": "#/definitions/TemplateFile"
      },
      "type": "array",
      "minItems": 1
    },
    "name": {
      "title": "Name of the template",
      "type": "string"
    },
    "slug": {
      "title": "Slug of the template",
      "description": "Slug has to be unique and match the tempalte folder, to be included into the generator",
      "type": "string"
    },
    "dataTypes": {
      "title": "Replace data types, original type as key, new type as value",
      "additionalProperties": {
        "type":"string"
      },
      "type":"object"
    },
    "serviceData": {
      "title": "Add data to each service, to use in your templates",
      "additionalProperties": {
        "title": "Use the exact service name as key",
        "type":"object"
      },
      "type":"object"
    },
    "license": {
      "title": "License of the template",
      "description": "'MIT' is required to be included into the generator",
      "default": "MIT",
      "type":"string"
    }
  },
  "required": [
    "author",
    "files",
    "slug"
  ],
  "type": "object"
}

=== svrooij/sonos-api-docs/generator/sonos-docs/templates/ts/template.json
{
  "$schema": "https://svrooij.io/sonos-api-docs/schema/template.json",
  "name": "Sonos Typescript documentation",
  "slug": "ts",
  "author": {
    "name": "svrooij",
    "link": "https://svrooij.io"
  },
  "files": [
    {
      "file": "docs-service.hbs",
      "outputFile": "docs/sonos-device/services/{snService}-service.md",
      "usage":"service"
    },
    {
      "file": "docs-index.hbs",
      "outputFile": "docs/sonos-device/services/services.md",
      "usage":"index"
    },
    {
      "file": "service.hbs",
      "outputFile": "src/services/{snService}.service.ts",
      "usage":"service"
    },
    {
      "file": "service-export.hbs",
      "outputFile": "src/services/index.ts",
      "usage":"index"
    },
    {
      "file": "sonos-base.hbs",
      "outputFile": "src/sonos-device-base.ts",
      "usage":"index"
    }
  ],
  "dataTypes": {
    "ui4": "number",
    "i4": "number",
    "ui2": "number",
    "i2": "number",
    "MetaData": "Track | string",
    "PlayMode": "PlayMode",
    "ZoneGroupState": "Array<ZoneGroup> | string"
  },
  "serviceData": {
    "AlarmClockService": {
      "extended": true,
      "imports": ["Alarm", "PatchAlarm", "PlayMode", "Track"],
      "importArrayHelper": true,
      "importMetadataHelper": true,
      "importXmlHelper": true
    },
    "AVTransportService": {
      "imports": ["PlayMode", "Track"]
    },
    "ContentDirectoryService": {
      "extended": true,
      "imports": ["BrowseResponse"],
      "importArrayHelper": true,
      "importMetadataHelper": true,
      "importXmlHelper": true
    },
    "MusicServicesService": {
      "extended": true,
      "importArrayHelper": true,
      "importXmlHelper": true
    },
    "QueueService": {
      "imports": ["BrowseResponse", "Track"]
    },
    "RenderingControlService": {
      "extended": true,
      "imports": ["ChannelValue"]
    },
    "VirtualLineInService": {
      "imports":["Track"]
    },
    "ZoneGroupTopologyService": {
      "extended": true,
      "importArrayHelper": true,
      "importUrl": true,
      "importXmlHelper": true
    }
  },
  "license": "MIT"
}
